Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = 'foreman.stage0.local'

    # https://www.vagrantup.com/docs/providers/ for information on providers.
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end

    # Sync over entire Salt state repository. The minion will run masterless.
    # https://www.vagrantup.com/docs/synced-folders/ for information on folder sharing.
    config.vm.synced_folder "salt", "/srv/salt", type: "virtualbox"
    # Disable default shared folder.
    config.vm.synced_folder ".", "/vagrant", disabled: true


    # Fixed network address to debug Foreman functionality with other VM's.
    config.vm.network "private_network", ip: "192.168.200.10"
    # Bridge to the Host connected network, to provision other bare metal.
    # config.vm.network "public_network"

    # https://www.vagrantup.com/docs/provisioning/ for information on VM provisioning.
    config.vm.provision :salt do |salt|
        salt.install_type = "stable"
        salt.minion_config = "salt/minion.conf.yaml"
        salt.masterless = true
        salt.run_highstate = true
    end
end